version: '3.8'

services:
  frontend:
    image: bankfrontend
    container_name: frontend
    networks:
      - bankapp

  backend:
    image: bankbackend
    container_name: backend
    networks:
      - bankapp
    depends_on:
      mysql:
        condition: service_healthy
    ports:
    - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: learn_db
    ports:
      - "3306:3306"
    networks:
      - bankapp
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20


  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/deafult.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bankapp
    depends_on:
      - backend
      - frontend
    restart: always

    

networks:
  bankapp:
    driver: bridge

volumes:
  mysql_data:
